<a href="https://colab.research.google.com/github/min20120907/Make_a_neural_network/blob/master/CNN%E6%B8%AC%E8%A9%A6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Copying files from external Google Drive...")
! cp /content/drive/My\ Drive/captcha.zip .
print("Copied files!")
! unzip -qq captcha.zip
print("Unzipping the dataset...")
! rm captcha.zip
print("Removed the archives!")


Copying files from external Google Drive...
Copied files!
replace testing/583482.png? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
Unzipping the dataset...
Removed the archives!


In [ ]:
# Training Process
import numpy as np
import os
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.utils import to_categorical, plot_model

x_list = list()
y_list = list()
x_train = list()
y_train = list()
x_test = list()
y_test = list()

# load data
for img_filename in os.listdir('training/'):
    if img_filename.endswith('.png'):
        img = load_img('training/' + img_filename, color_mode='grayscale')
        img_array = img_to_array(img)
        for i in range(6):
            x_list.append(img_array[:, i*20:(i+1)*20] / 255.0)
            y_list.append(img_filename[i])

y_list = to_categorical(y_list, num_classes=10)

# split data into training set and testing set
x_train, x_test, y_train, y_test = train_test_split(x_list, y_list, train_size=0.8)

# model
model = Sequential()
model.add(Conv2D(8, kernel_size=(3, 3), activation='relu', input_shape=(32, 20, 1)))
model.add(Conv2D(16, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(32, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])

plot_model(model, to_file='model.png', show_shapes=True, dpi=300)

epochs = 1000

# start training
history = model.fit(np.array(x_train), np.array(y_train), epochs=epochs, validation_data=(np.array(x_test), np.array(y_test)))

# evaluate model
loss, accuracy = model.evaluate(np.array(x_test), np.array(y_test))
print('Test loss:', loss)
print('Test accuracy:', accuracy)

# save the model
model.save('cnn_model.h5')
print("Model saved successfully! ")

Epoch 1/1000
15/15 [==============================] - 0s 12ms/step - loss: 2.2968 - accuracy: 0.1021 - val_loss: 2.2684 - val_accuracy: 0.1250
Epoch 2/1000
15/15 [==============================] - 0s 4ms/step - loss: 2.2461 - accuracy: 0.1604 - val_loss: 2.1791 - val_accuracy: 0.2833
Epoch 3/1000
15/15 [==============================] - 0s 4ms/step - loss: 2.1520 - accuracy: 0.3271 - val_loss: 2.0401 - val_accuracy: 0.3750
Epoch 4/1000
15/15 [==============================] - 0s 4ms/step - loss: 1.9630 - accuracy: 0.4313 - val_loss: 1.8032 - val_accuracy: 0.3917
Epoch 5/1000
15/15 [==============================] - 0s 4ms/step - loss: 1.6831 - accuracy: 0.4917 - val_loss: 1.4978 - val_accuracy: 0.5750
Epoch 6/1000
15/15 [==============================] - 0s 4ms/step - loss: 1.4038 - accuracy: 0.5833 - val_loss: 1.2536 - val_accuracy: 0.6000
Epoch 7/1000
15/15 [==============================] - 0s 4ms/step - loss: 1.0652 - accuracy: 0.7042 - val_loss: 1.0148 - val_accuracy: 0.6333
Epoch

In [ ]:
# Predicting Process
import numpy as np
from tensorflow.keras import models
from tensorflow.keras.preprocessing.image import load_img, img_to_array

np.set_printoptions(suppress=True, linewidth=150, precision=9, formatter={'float': '{: 0.9f}'.format})

# load model
model = models.load_model('cnn_model.h5')

# load img to predict
img_filename = input('Varification code img filename: ')
img = load_img(img_filename, color_mode='grayscale')
img_array = img_to_array(img)

# split the 6 digits
x_list = list()
for i in range(6):
    x_list.append(img_array[:, i*20:(i+1)*20] / 255.0)

# predict
print(model.predict(np.array(x_list)))
print(model.predict_classes(np.array(x_list)))

Varification code img filename: testing/267221.png
[[ 0.000000000  0.000000000  1.000000000  0.000000000  0.000000000  0.000000000  0.000000000  0.000000000  0.000000000  0.000000000]
 [ 0.363303483  0.000000000  0.000000000  0.000000080  0.000000000  0.169808894  0.011546289  0.000000000  0.000003279  0.455338001]
 [ 0.000000000  0.000000000  0.000000000  0.000000000  0.000000000  0.000000000  0.000000000  1.000000000  0.000000000  0.000000000]
 [ 0.000000046  0.015572998  0.984077215  0.000033855  0.000000000  0.000000291  0.000000000  0.000313476  0.000000000  0.000001977]
 [ 0.000000000  0.000000000  1.000000000  0.000000000  0.000000000  0.000000000  0.000000000  0.000000000  0.000000000  0.000000000]
 [ 0.000000000  0.998936594  0.000000000  0.000000001  0.001063434  0.000000000  0.000000000  0.000000010  0.000000000  0.000000000]]
[2 9 7 2 2 1]
